// assets/iconst/codepoints.txt
export enum Icons {
    Dashboard = "&#xe871;",
    List = "&#xe896;",
    People = "&#xe7fb;",
    Person = "&#xe7fd;",
    ChevronLeft = "&#xe5cb;",
    ChevronRight = "&#xe5cc;",
    ExpandMore = "&#xe5cf;",
    Exit = "&#xe879;",
    Menu = "&#xe5d2",
    ArrowBack = "&#xe5c4;",
    Search = "&#xe8b6;",
    SwapVert = "&#xe8d5;",
    ArrowDropDown = "&#xe5c5;",
    ArrowUp = "&#xe5d8;",
    ArrowDown = "&#xe5db;",
    Add = "&#xe145;",
    Edit = "&#xe3c9;",
    Delete = "&#xe872;",
    ShoppingCart = "&#xe8cc;",
    Restore = "&#xe8b3;",
    Close = "&#xe5cd;",
    Category = "&#xe574;",
    CreditCard = "&#xe870;",
    AccountBalance = "&#xe84f;",
    Wallet = "&#xe850;"
}
